// Work examples come from src/data/content.js. Demos are separate from project evidence.
export const skillCapabilities = [
  { id: 'figma', name: '화면 디자인', tools: 'Figma',
    lead: '필요한 정보를 찾기 쉽게 화면을 디자인합니다.',
    description: '글과 사진, 버튼의 위치를 정하고 다음 화면으로 어떻게 이어질지 설계합니다.',
    project: 'animal24', work: '보호동물을 먼저 찾아볼 수 있도록 검색과 동물 목록을 앞에 배치했습니다.',
    method: '자주 쓰는 버튼과 카드를 같은 규칙으로 만들고, 화면을 연결해 사용 순서를 확인합니다. Figma에서는 이를 컴포넌트와 프로토타입으로 관리합니다.', demo: 'design' },
  { id: 'react', name: '웹 화면 만들기', tools: 'HTML · CSS · React',
    lead: '디자인한 화면을 실제로 사용할 수 있게 만듭니다.',
    description: '컴퓨터와 휴대폰에 맞춰 화면을 배치하고, 여러 화면에서 쓰는 버튼과 메뉴를 만듭니다.',
    project: 'jaduya', work: '로그인·홈·소비 화면을 만들고, 선택한 계정과 소비 내역을 알아보기 쉽게 다듬고 있습니다.',
    method: 'HTML로 내용의 순서를 정하고 CSS로 크기와 배치를 조절합니다. React로 반복되는 화면 조각을 만들고 선택 상태에 따라 내용을 갱신합니다.', demo: 'responsive' },
  { id: 'javascript', name: '클릭에 반응하기', tools: 'JavaScript',
    lead: '누르거나 움직이면 화면이 반응하게 만듭니다.',
    description: '작은 사진을 누르면 큰 사진이 바뀌고, 메뉴를 누르면 필요한 내용이 열리는 동작을 만듭니다.',
    project: 'sulwhasoo', work: '제품 상세 페이지에서 화면을 내리면 이미지가 나타나고 이동하는 효과와 리뷰 슬라이드를 구현했습니다.',
    method: '클릭과 스크롤 같은 입력을 읽고, 그에 맞춰 화면의 내용과 표시 상태를 바꿉니다. 이 페이지의 수정 선택과 정보 패널도 같은 원리로 동작합니다.', demo: 'gallery' },
  { id: 'gsap', name: '움직임 만들기', tools: 'GSAP',
    lead: '화면이 나타나고 바뀌는 움직임을 만듭니다.',
    description: '여러 요소가 어떤 순서로, 얼마나 빠르게 움직일지 조절합니다.',
    work: '아래 예시에서는 사진과 설명이 순서대로 나타납니다. GSAP으로 직접 실행해 볼 수 있습니다.',
    method: '각 움직임을 타임라인에 연결해 순서와 시간을 조절합니다. 동작 줄이기 설정에서는 움직임 없이 내용을 바로 표시합니다.', demo: 'motion' },
  { id: 'chatgpt', name: 'AI로 제작 돕기', tools: 'ChatGPT · Claude · Higgsfield',
    lead: 'AI로 초안을 만들고, 직접 확인하며 다듬습니다.',
    description: '아이디어 정리와 그림·코드 초안에 도움을 받고, 의도한 디자인과 실제 동작에 맞는지 확인합니다.',
    work: '이 포트폴리오의 배경에는 생성 이미지를 사용했습니다. 메뉴와 버튼, 글은 이미지와 분리해 실제로 작동하도록 구현했습니다.',
    image: '/assets/production/images/skills-world/courtyard-v3.webp', imageAlt: 'Skills 공간에 실제 사용한 낮의 석재 안뜰 배경', caption: '현재 페이지에 사용한 생성 배경',
    method: 'ChatGPT와 Claude로 요구사항·아이디어를 정리하고, Claude Code로 구현과 오류 점검을 보조합니다. Higgsfield는 시각 자산과 장면 참고에 활용합니다. 결과물은 그대로 확정하지 않고 확인합니다.', portfolio: true },
  { id: 'git', name: '함께 작업하기', tools: 'Git · GitHub',
    lead: '수정 기록을 남기고, 팀의 코드를 합칩니다.',
    description: '무엇을 바꿨는지 기록해 이전 작업을 확인하고, 여러 사람이 고친 부분이 잘 연결되도록 정리합니다.',
    project: 'sulwhasoo', work: '팀 코드를 합칠 때 같은 부분이 다르게 수정된 충돌을 해결하고, 빠진 모션 스크립트 선언을 점검했습니다.',
    method: '작업별 브랜치에서 변경하고 커밋으로 기록합니다. 코드를 합칠 때 충돌한 부분을 확인하고, 합친 뒤 실제 화면을 실행해 검증합니다.' },
]

export const simpleTools = {
  figma: '글과 버튼의 위치를 정하고 화면을 디자인합니다.',
  photoshop: '사진의 색을 보정하고 필요한 이미지를 합성합니다.',
  illustrator: '크기를 바꿔도 선명한 아이콘과 그림을 만듭니다.',
  html: '제목, 글, 사진처럼 웹 페이지에 들어갈 내용을 구성합니다.',
  css: '글의 크기와 색, 화면의 배치를 정합니다.',
  javascript: '클릭이나 스크롤에 맞춰 화면이 반응하게 합니다.',
  react: '반복되는 버튼과 화면을 만들고, 선택에 따라 내용을 바꿉니다.',
  vite: '수정한 웹 화면을 빠르게 확인하고 배포할 파일로 묶습니다.',
  gsap: '여러 요소의 움직임과 순서, 속도를 조절합니다.',
  scrolltrigger: '페이지를 내린 위치에 맞춰 움직임을 실행하는 도구입니다. 이 페이지에서는 이동 진행 예시로 원리를 설명합니다.',
  swiper: '사진이나 내용을 옆으로 넘겨 볼 수 있게 만듭니다.',
  lenis: '페이지를 내릴 때 움직이는 속도와 감속을 조절합니다.',
  three: '웹에서 입체 물체를 보여주고 회전하는 방법을 실험하고 있습니다.',
  claude: '생각과 요구사항을 정리하고 디자인 방향을 검토할 때 도움을 받습니다.',
  'claude-code': '코드를 읽고 수정하거나 오류를 찾을 때 도움을 받습니다.',
  chatgpt: '아이디어와 이미지·코드 초안을 만들고 검토할 때 도움을 받습니다.',
  higgsfield: '이미지와 영상의 장면을 구상하고 시각 자료를 제작하는 데 활용합니다.',
  'vs-code': '코드를 작성하고 수정하는 편집기입니다.',
  git: '수정 기록을 남기는 Git과 코드를 공유하는 GitHub를 함께 사용합니다.',
  npm: '프로젝트에 필요한 도구를 설치하고 관리합니다.',
  vercel: '완성한 웹 페이지를 인터넷에서 열어 볼 수 있게 배포하는 서비스입니다.',
}
