const {chromium}=require('C:/Users/EZEN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({viewport:{width:1440,height:810}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5174/projects');await p.waitForTimeout(600);await p.keyboard.down('a');await p.waitForTimeout(500);await p.keyboard.up('a');if(Number(await p.locator('.gallery-walker').getAttribute('data-x'))>=49)throw Error('WASD failed');
for(const name of ['자두야','마실로','국가동물24','설화수']){await p.getByRole('button',{name:name+' 선택',exact:true}).click();if(!await p.locator('.gallery-project-hud').innerText().then(s=>s.includes(name)))throw Error('selection '+name)}
await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(150);await p.locator('.gallery-floor').evaluate(el=>{const r=el.closest('.gallery-stage').getBoundingClientRect();el.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1,clientX:r.left+r.width*.34,clientY:r.top+r.height*.65}))});await p.keyboard.press('e');if(await p.getByRole('button',{name:'마실로 선택',exact:true}).getAttribute('aria-pressed')!=='true')throw Error('proximity E failed');await p.locator('.gallery-project-hud a').click();if(!p.url().includes('/projects/masillo'))throw Error('case route failed');await p.goBack();await p.emulateMedia({reducedMotion:'no-preference'});
const sizes=[[2560,1440],[1920,1080],[1440,810],[1366,768],[1180,820],[1024,768],[768,1024],[430,932],[402,874],[390,844],[360,800],[767,900],[1023,800],[1279,800],[1280,800],[1919,1080],[1920,1080]];const results=[];
for(const [w,h]of sizes){await p.setViewportSize({width:w,height:h});await p.waitForTimeout(50);results.push({w,h,overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),navLinks:await p.locator('.gallery-top-nav a').count()});if(w===1920&&h===1080)await p.screenshot({path:'docs/projects-gallery-desktop.png'});if(w===430)await p.screenshot({path:'docs/projects-gallery-mobile.png'})}
await p.setViewportSize({width:1440,height:810});await p.getByRole('button',{name:'국가동물24 선택',exact:true}).click();await p.screenshot({path:'docs/projects-gallery-selected.png'});await p.locator('.gallery-menu summary').click();await p.getByRole('button',{name:'움직임 멈추기',exact:true}).click();const paused=await p.locator('.project-gallery').getAttribute('data-still');if(paused!=='true')throw Error('pause failed');
fs.writeFileSync('docs/projects-gallery-qa.json',JSON.stringify({errors,checks:['WASD movement','four exhibit click selections','reduced-motion proximity + E','case-study routing and browser back','motion pause'],viewports:results},null,2));console.log(JSON.stringify({errors,viewports:results.length,overflow:results.filter(r=>r.overflow)}));await b.close()})();
